(function (Scratch) {
    "use strict";

	// Author: kitedriver
    class WebTTS {
        constructor(runtime) {
            this.runtime = runtime;
            // 直接固定三项默认声音
            this.voiceArr = [
{text: 'Microsoft Huihui - Chinese (Simplified, PRC) (zh-CN)', value: 'Microsoft Huihui - Chinese (Simplified, PRC)'}, 
{text: 'Microsoft Kangkang - Chinese (Simplified, PRC) (zh-CN)', value: 'Microsoft Kangkang - Chinese (Simplified, PRC)'}, 
{text: 'Microsoft Yaoyao - Chinese (Simplified, PRC) (zh-CN)', value: 'Microsoft Yaoyao - Chinese (Simplified, PRC)'}, 
{text: 'Microsoft Adri Online (Natural) - Afrikaans (South Africa) (af-ZA)', value: 'Microsoft Adri Online (Natural) - Afrikaans (South Africa)'}, 
{text: 'Microsoft Willem Online (Natural) - Afrikaans (South Africa) (af-ZA)', value: 'Microsoft Willem Online (Natural) - Afrikaans (South Africa)'}, 
{text: 'Microsoft Anila Online (Natural) - Albanian (Albania) (sq-AL)', value: 'Microsoft Anila Online (Natural) - Albanian (Albania)'}, 
{text: 'Microsoft Ilir Online (Natural) - Albanian (Albania) (sq-AL)', value: 'Microsoft Ilir Online (Natural) - Albanian (Albania)'}, 
{text: 'Microsoft Ameha Online (Natural) - Amharic (Ethiopia) (am-ET)', value: 'Microsoft Ameha Online (Natural) - Amharic (Ethiopia)'}, 
{text: 'Microsoft Mekdes Online (Natural) - Amharic (Ethiopia) (am-ET)', value: 'Microsoft Mekdes Online (Natural) - Amharic (Ethiopia)'}, 
{text: 'Microsoft Amina Online (Natural) - Arabic (Algeria) (ar-DZ)', value: 'Microsoft Amina Online (Natural) - Arabic (Algeria)'}, 
{text: 'Microsoft Ismael Online (Natural) - Arabic (Algeria) (ar-DZ)', value: 'Microsoft Ismael Online (Natural) - Arabic (Algeria)'}, 
{text: 'Microsoft Ali Online (Natural) - Arabic (Bahrain) (ar-BH)', value: 'Microsoft Ali Online (Natural) - Arabic (Bahrain)'}, 
{text: 'Microsoft Laila Online (Natural) - Arabic (Bahrain) (ar-BH)', value: 'Microsoft Laila Online (Natural) - Arabic (Bahrain)'}, 
{text: 'Microsoft Salma Online (Natural) - Arabic (Egypt) (ar-EG)', value: 'Microsoft Salma Online (Natural) - Arabic (Egypt)'}, 
{text: 'Microsoft Shakir Online (Natural) - Arabic (Egypt) (ar-EG)', value: 'Microsoft Shakir Online (Natural) - Arabic (Egypt)'}, 
{text: 'Microsoft Bassel Online (Natural) - Arabic (Iraq) (ar-IQ)', value: 'Microsoft Bassel Online (Natural) - Arabic (Iraq)'}, 
{text: 'Microsoft Rana Online (Natural) - Arabic (Iraq) (ar-IQ)', value: 'Microsoft Rana Online (Natural) - Arabic (Iraq)'}, 
{text: 'Microsoft Sana Online (Natural) - Arabic (Jordan) (ar-JO)', value: 'Microsoft Sana Online (Natural) - Arabic (Jordan)'}, 
{text: 'Microsoft Taim Online (Natural) - Arabic (Jordan) (ar-JO)', value: 'Microsoft Taim Online (Natural) - Arabic (Jordan)'}, 
{text: 'Microsoft Fahed Online (Natural) - Arabic (Kuwait) (ar-KW)', value: 'Microsoft Fahed Online (Natural) - Arabic (Kuwait)'}, 
{text: 'Microsoft Noura Online (Natural) - Arabic (Kuwait) (ar-KW)', value: 'Microsoft Noura Online (Natural) - Arabic (Kuwait)'}, 
{text: 'Microsoft Layla Online (Natural) - Arabic (Lebanon) (ar-LB)', value: 'Microsoft Layla Online (Natural) - Arabic (Lebanon)'}, 
{text: 'Microsoft Rami Online (Natural) - Arabic (Lebanon) (ar-LB)', value: 'Microsoft Rami Online (Natural) - Arabic (Lebanon)'}, 
{text: 'Microsoft Iman Online (Natural) - Arabic (Libya) (ar-LY)', value: 'Microsoft Iman Online (Natural) - Arabic (Libya)'}, 
{text: 'Microsoft Omar Online (Natural) - Arabic (Libya) (ar-LY)', value: 'Microsoft Omar Online (Natural) - Arabic (Libya)'}, 
{text: 'Microsoft Jamal Online (Natural) - Arabic (Morocco) (ar-MA)', value: 'Microsoft Jamal Online (Natural) - Arabic (Morocco)'}, 
{text: 'Microsoft Mouna Online (Natural) - Arabic (Morocco) (ar-MA)', value: 'Microsoft Mouna Online (Natural) - Arabic (Morocco)'}, 
{text: 'Microsoft Abdullah Online (Natural) - Arabic (Oman) (ar-OM)', value: 'Microsoft Abdullah Online (Natural) - Arabic (Oman)'}, 
{text: 'Microsoft Aysha Online (Natural) - Arabic (Oman) (ar-OM)', value: 'Microsoft Aysha Online (Natural) - Arabic (Oman)'}, 
{text: 'Microsoft Amal Online (Natural) - Arabic (Qatar) (ar-QA)', value: 'Microsoft Amal Online (Natural) - Arabic (Qatar)'}, 
{text: 'Microsoft Moaz Online (Natural) - Arabic (Qatar) (ar-QA)', value: 'Microsoft Moaz Online (Natural) - Arabic (Qatar)'}, 
{text: 'Microsoft Hamed Online (Natural) - Arabic (Saudi Arabia) (ar-SA)', value: 'Microsoft Hamed Online (Natural) - Arabic (Saudi Arabia)'}, 
{text: 'Microsoft Zariyah Online (Natural) - Arabic (Saudi Arabia) (ar-SA)', value: 'Microsoft Zariyah Online (Natural) - Arabic (Saudi Arabia)'}, 
{text: 'Microsoft Amany Online (Natural) - Arabic (Syria) (ar-SY)', value: 'Microsoft Amany Online (Natural) - Arabic (Syria)'}, 
{text: 'Microsoft Laith Online (Natural) - Arabic (Syria) (ar-SY)', value: 'Microsoft Laith Online (Natural) - Arabic (Syria)'}, 
{text: 'Microsoft Hedi Online (Natural) - Arabic (Tunisia) (ar-TN)', value: 'Microsoft Hedi Online (Natural) - Arabic (Tunisia)'}, 
{text: 'Microsoft Reem Online (Natural) - Arabic (Tunisia) (ar-TN)', value: 'Microsoft Reem Online (Natural) - Arabic (Tunisia)'}, 
{text: 'Microsoft Fatima Online (Natural) - Arabic (United Arab Emirates) (ar-AE)', value: 'Microsoft Fatima Online (Natural) - Arabic (United Arab Emirates)'}, 
{text: 'Microsoft Hamdan Online (Natural) - Arabic (United Arab Emirates) (ar-AE)', value: 'Microsoft Hamdan Online (Natural) - Arabic (United Arab Emirates)'}, 
{text: 'Microsoft Maryam Online (Natural) - Arabic (Yemen) (ar-YE)', value: 'Microsoft Maryam Online (Natural) - Arabic (Yemen)'}, 
{text: 'Microsoft Saleh Online (Natural) - Arabic (Yemen) (ar-YE)', value: 'Microsoft Saleh Online (Natural) - Arabic (Yemen)'}, 
{text: 'Microsoft Babek Online (Natural) - Azerbaijani (Azerbaijan) (az-AZ)', value: 'Microsoft Babek Online (Natural) - Azerbaijani (Azerbaijan)'}, 
{text: 'Microsoft Banu Online (Natural) - Azerbaijani (Azerbaijan) (az-AZ)', value: 'Microsoft Banu Online (Natural) - Azerbaijani (Azerbaijan)'}, 
{text: 'Microsoft Nabanita Online (Natural) - Bangla (Bangladesh) (bn-BD)', value: 'Microsoft Nabanita Online (Natural) - Bangla (Bangladesh)'}, 
{text: 'Microsoft Pradeep Online (Natural) - Bangla (Bangladesh) (bn-BD)', value: 'Microsoft Pradeep Online (Natural) - Bangla (Bangladesh)'}, 
{text: 'Microsoft Bashkar Online (Natural) - Bangla (India) (bn-IN)', value: 'Microsoft Bashkar Online (Natural) - Bangla (India)'}, 
{text: 'Microsoft Tanishaa Online (Natural) - Bengali (India) (bn-IN)', value: 'Microsoft Tanishaa Online (Natural) - Bengali (India)'}, 
{text: 'Microsoft Vesna Online (Natural) - Bosnian (Bosnia and Herzegovina) (bs-BA)', value: 'Microsoft Vesna Online (Natural) - Bosnian (Bosnia and Herzegovina)'}, 
{text: 'Microsoft Goran Online (Natural) - Bosnian (Bosnia) (bs-BA)', value: 'Microsoft Goran Online (Natural) - Bosnian (Bosnia)'}, 
{text: 'Microsoft Borislav Online (Natural) - Bulgarian (Bulgaria) (bg-BG)', value: 'Microsoft Borislav Online (Natural) - Bulgarian (Bulgaria)'}, 
{text: 'Microsoft Kalina Online (Natural) - Bulgarian (Bulgaria) (bg-BG)', value: 'Microsoft Kalina Online (Natural) - Bulgarian (Bulgaria)'}, 
{text: 'Microsoft Nilar Online (Natural) - Burmese (Myanmar) (my-MM)', value: 'Microsoft Nilar Online (Natural) - Burmese (Myanmar)'}, 
{text: 'Microsoft Thiha Online (Natural) - Burmese (Myanmar) (my-MM)', value: 'Microsoft Thiha Online (Natural) - Burmese (Myanmar)'}, 
{text: 'Microsoft Enric Online (Natural) - Catalan (ca-ES)', value: 'Microsoft Enric Online (Natural) - Catalan'}, 
{text: 'Microsoft Joana Online (Natural) - Catalan (ca-ES)', value: 'Microsoft Joana Online (Natural) - Catalan'}, 
{text: 'Microsoft HiuGaai Online (Natural) - Chinese (Cantonese Traditional) (zh-HK)', value: 'Microsoft HiuGaai Online (Natural) - Chinese (Cantonese Traditional)'}, 
{text: 'Microsoft HiuMaan Online (Natural) - Chinese (Hong Kong SAR) (zh-HK)', value: 'Microsoft HiuMaan Online (Natural) - Chinese (Hong Kong SAR)'}, 
{text: 'Microsoft WanLung Online (Natural) - Chinese (Hong Kong SAR) (zh-HK)', value: 'Microsoft WanLung Online (Natural) - Chinese (Hong Kong SAR)'}, 
{text: 'Microsoft Xiaoxiao Online (Natural) - Chinese (Mainland) (zh-CN)', value: 'Microsoft Xiaoxiao Online (Natural) - Chinese (Mainland)'}, 
{text: 'Microsoft Xiaoyi Online (Natural) - Chinese (Mainland) (zh-CN)', value: 'Microsoft Xiaoyi Online (Natural) - Chinese (Mainland)'}, 
{text: 'Microsoft Yunjian Online (Natural) - Chinese (Mainland) (zh-CN)', value: 'Microsoft Yunjian Online (Natural) - Chinese (Mainland)'}, 
{text: 'Microsoft Yunxi Online (Natural) - Chinese (Mainland) (zh-CN)', value: 'Microsoft Yunxi Online (Natural) - Chinese (Mainland)'}, 
{text: 'Microsoft Yunxia Online (Natural) - Chinese (Mainland) (zh-CN)', value: 'Microsoft Yunxia Online (Natural) - Chinese (Mainland)'}, 
{text: 'Microsoft Yunyang Online (Natural) - Chinese (Mainland) (zh-CN)', value: 'Microsoft Yunyang Online (Natural) - Chinese (Mainland)'}, 
{text: 'Microsoft Xiaobei Online (Natural) - Chinese (Northeastern Mandarin) (zh-CN-liaoning)', value: 'Microsoft Xiaobei Online (Natural) - Chinese (Northeastern Mandarin)'}, 
{text: 'Microsoft HsiaoChen Online (Natural) - Chinese (Taiwan) (zh-TW)', value: 'Microsoft HsiaoChen Online (Natural) - Chinese (Taiwan)'}, 
{text: 'Microsoft YunJhe Online (Natural) - Chinese (Taiwan) (zh-TW)', value: 'Microsoft YunJhe Online (Natural) - Chinese (Taiwan)'}, 
{text: 'Microsoft HsiaoYu Online (Natural) - Chinese (Taiwanese Mandarin) (zh-TW)', value: 'Microsoft HsiaoYu Online (Natural) - Chinese (Taiwanese Mandarin)'}, 
{text: 'Microsoft Xiaoni Online (Natural) - Chinese (Zhongyuan Mandarin Shaanxi) (zh-CN-shaanxi)', value: 'Microsoft Xiaoni Online (Natural) - Chinese (Zhongyuan Mandarin Shaanxi)'}, 
{text: 'Microsoft Gabrijela Online (Natural) - Croatian (Croatia) (hr-HR)', value: 'Microsoft Gabrijela Online (Natural) - Croatian (Croatia)'}, 
{text: 'Microsoft Srecko Online (Natural) - Croatian (Croatia) (hr-HR)', value: 'Microsoft Srecko Online (Natural) - Croatian (Croatia)'}, 
{text: 'Microsoft Antonin Online (Natural) - Czech (Czech) (cs-CZ)', value: 'Microsoft Antonin Online (Natural) - Czech (Czech)'}, 
{text: 'Microsoft Vlasta Online (Natural) - Czech (Czech) (cs-CZ)', value: 'Microsoft Vlasta Online (Natural) - Czech (Czech)'}, 
{text: 'Microsoft Christel Online (Natural) - Danish (Denmark) (da-DK)', value: 'Microsoft Christel Online (Natural) - Danish (Denmark)'}, 
{text: 'Microsoft Jeppe Online (Natural) - Danish (Denmark) (da-DK)', value: 'Microsoft Jeppe Online (Natural) - Danish (Denmark)'}, 
{text: 'Microsoft Arnaud Online (Natural) - Dutch (Belgium) (nl-BE)', value: 'Microsoft Arnaud Online (Natural) - Dutch (Belgium)'}, 
{text: 'Microsoft Dena Online (Natural) - Dutch (Belgium) (nl-BE)', value: 'Microsoft Dena Online (Natural) - Dutch (Belgium)'}, 
{text: 'Microsoft Colette Online (Natural) - Dutch (Netherlands) (nl-NL)', value: 'Microsoft Colette Online (Natural) - Dutch (Netherlands)'}, 
{text: 'Microsoft Fenna Online (Natural) - Dutch (Netherlands) (nl-NL)', value: 'Microsoft Fenna Online (Natural) - Dutch (Netherlands)'}, 
{text: 'Microsoft Maarten Online (Natural) - Dutch (Netherlands) (nl-NL)', value: 'Microsoft Maarten Online (Natural) - Dutch (Netherlands)'}, 
{text: 'Microsoft Natasha Online (Natural) - English (Australia) (en-AU)', value: 'Microsoft Natasha Online (Natural) - English (Australia)'}, 
{text: 'Microsoft William Online (Natural) - English (Australia) (en-AU)', value: 'Microsoft William Online (Natural) - English (Australia)'}, 
{text: 'Microsoft Clara Online (Natural) - English (Canada) (en-CA)', value: 'Microsoft Clara Online (Natural) - English (Canada)'}, 
{text: 'Microsoft Liam Online (Natural) - English (Canada) (en-CA)', value: 'Microsoft Liam Online (Natural) - English (Canada)'}, 
{text: 'Microsoft Yan Online (Natural) - English (Hong Kong SAR) (en-HK)', value: 'Microsoft Yan Online (Natural) - English (Hong Kong SAR)'}, 
{text: 'Microsoft Sam Online (Natural) - English (Hongkong) (en-HK)', value: 'Microsoft Sam Online (Natural) - English (Hongkong)'}, 
{text: 'Microsoft Neerja Online (Natural) - English (India) (Preview) (en-IN)', value: 'Microsoft Neerja Online (Natural) - English (India) (Preview)'}, 
{text: 'Microsoft Neerja Online (Natural) - English (India) (en-IN)', value: 'Microsoft Neerja Online (Natural) - English (India)'}, 
{text: 'Microsoft Prabhat Online (Natural) - English (India) (en-IN)', value: 'Microsoft Prabhat Online (Natural) - English (India)'}, 
{text: 'Microsoft Connor Online (Natural) - English (Ireland) (en-IE)', value: 'Microsoft Connor Online (Natural) - English (Ireland)'}, 
{text: 'Microsoft Emily Online (Natural) - English (Ireland) (en-IE)', value: 'Microsoft Emily Online (Natural) - English (Ireland)'}, 
{text: 'Microsoft Asilia Online (Natural) - English (Kenya) (en-KE)', value: 'Microsoft Asilia Online (Natural) - English (Kenya)'}, 
{text: 'Microsoft Chilemba Online (Natural) - English (Kenya) (en-KE)', value: 'Microsoft Chilemba Online (Natural) - English (Kenya)'}, 
{text: 'Microsoft Mitchell Online (Natural) - English (New Zealand) (en-NZ)', value: 'Microsoft Mitchell Online (Natural) - English (New Zealand)'}, 
{text: 'Microsoft Molly Online (Natural) - English (New Zealand) (en-NZ)', value: 'Microsoft Molly Online (Natural) - English (New Zealand)'}, 
{text: 'Microsoft Abeo Online (Natural) - English (Nigeria) (en-NG)', value: 'Microsoft Abeo Online (Natural) - English (Nigeria)'}, 
{text: 'Microsoft Ezinne Online (Natural) - English (Nigeria) (en-NG)', value: 'Microsoft Ezinne Online (Natural) - English (Nigeria)'}, 
{text: 'Microsoft James Online (Natural) - English (Philippines) (en-PH)', value: 'Microsoft James Online (Natural) - English (Philippines)'}, 
{text: 'Microsoft Rosa Online (Natural) - English (Philippines) (en-PH)', value: 'Microsoft Rosa Online (Natural) - English (Philippines)'}, 
{text: 'Microsoft Ava Online (Natural) - English (United States) (en-US)', value: 'Microsoft Ava Online (Natural) - English (United States)'},
{text: 'Microsoft Andrew Online (Natural) - English (United States) (en-US)', value: 'Microsoft Andrew Online (Natural) - English (United States)'}, 
{text: 'Microsoft Emma Online (Natural) - English (United States) (en-US)', value: 'Microsoft Emma Online (Natural) - English (United States)'}, 
{text: 'Microsoft Brian Online (Natural) - English (United States) (en-US)', value: 'Microsoft Brian Online (Natural) - English (United States)'}, 
{text: 'Microsoft Luna Online (Natural) - English (Singapore) (en-SG)', value: 'Microsoft Luna Online (Natural) - English (Singapore)'}, 
{text: 'Microsoft Wayne Online (Natural) - English (Singapore) (en-SG)', value: 'Microsoft Wayne Online (Natural) - English (Singapore)'}, 
{text: 'Microsoft Leah Online (Natural) - English (South Africa) (en-ZA)', value: 'Microsoft Leah Online (Natural) - English (South Africa)'}, 
{text: 'Microsoft Luke Online (Natural) - English (South Africa) (en-ZA)', value: 'Microsoft Luke Online (Natural) - English (South Africa)'}, 
{text: 'Microsoft Elimu Online (Natural) - English (Tanzania) (en-TZ)', value: 'Microsoft Elimu Online (Natural) - English (Tanzania)'}, 
{text: 'Microsoft Imani Online (Natural) - English (Tanzania) (en-TZ)', value: 'Microsoft Imani Online (Natural) - English (Tanzania)'}, 
{text: 'Microsoft Libby Online (Natural) - English (United Kingdom) (en-GB)', value: 'Microsoft Libby Online (Natural) - English (United Kingdom)'}, 
{text: 'Microsoft Maisie Online (Natural) - English (United Kingdom) (en-GB)', value: 'Microsoft Maisie Online (Natural) - English (United Kingdom)'}, 
{text: 'Microsoft Ryan Online (Natural) - English (United Kingdom) (en-GB)', value: 'Microsoft Ryan Online (Natural) - English (United Kingdom)'}, 
{text: 'Microsoft Sonia Online (Natural) - English (United Kingdom) (en-GB)', value: 'Microsoft Sonia Online (Natural) - English (United Kingdom)'}, 
{text: 'Microsoft Thomas Online (Natural) - English (United Kingdom) (en-GB)', value: 'Microsoft Thomas Online (Natural) - English (United Kingdom)'}, 
{text: 'Microsoft Ana Online (Natural) - English (United States) (en-US)', value: 'Microsoft Ana Online (Natural) - English (United States)'}, 
{text: 'Microsoft AndrewMultilingual Online (Natural) - English (United States) (en-US)', value: 'Microsoft AndrewMultilingual Online (Natural) - English (United States)'}, 
{text: 'Microsoft Aria Online (Natural) - English (United States) (en-US)', value: 'Microsoft Aria Online (Natural) - English (United States)'}, 
{text: 'Microsoft AvaMultilingual Online (Natural) - English (United States) (en-US)', value: 'Microsoft AvaMultilingual Online (Natural) - English (United States)'}, 
{text: 'Microsoft BrianMultilingual Online (Natural) - English (United States) (en-US)', value: 'Microsoft BrianMultilingual Online (Natural) - English (United States)'}, 
{text: 'Microsoft Christopher Online (Natural) - English (United States) (en-US)', value: 'Microsoft Christopher Online (Natural) - English (United States)'}, 
{text: 'Microsoft EmmaMultilingual Online (Natural) - English (United States) (en-US)', value: 'Microsoft EmmaMultilingual Online (Natural) - English (United States)'}, 
{text: 'Microsoft Eric Online (Natural) - English (United States) (en-US)', value: 'Microsoft Eric Online (Natural) - English (United States)'}, 
{text: 'Microsoft Guy Online (Natural) - English (United States) (en-US)', value: 'Microsoft Guy Online (Natural) - English (United States)'}, 
{text: 'Microsoft Jenny Online (Natural) - English (United States) (en-US)', value: 'Microsoft Jenny Online (Natural) - English (United States)'}, 
{text: 'Microsoft Michelle Online (Natural) - English (United States) (en-US)', value: 'Microsoft Michelle Online (Natural) - English (United States)'}, 
{text: 'Microsoft Roger Online (Natural) - English (United States) (en-US)', value: 'Microsoft Roger Online (Natural) - English (United States)'}, 
{text: 'Microsoft Steffan Online (Natural) - English (United States) (en-US)', value: 'Microsoft Steffan Online (Natural) - English (United States)'}, 
{text: 'Microsoft Anu Online (Natural) - Estonian (Estonia) (et-EE)', value: 'Microsoft Anu Online (Natural) - Estonian (Estonia)'}, 
{text: 'Microsoft Kert Online (Natural) - Estonian (Estonia) (et-EE)', value: 'Microsoft Kert Online (Natural) - Estonian (Estonia)'}, 
{text: 'Microsoft Angelo Online (Natural) - Filipino (Philippines) (fil-PH)', value: 'Microsoft Angelo Online (Natural) - Filipino (Philippines)'}, 
{text: 'Microsoft Blessica Online (Natural) - Filipino (Philippines) (fil-PH)', value: 'Microsoft Blessica Online (Natural) - Filipino (Philippines)'}, 
{text: 'Microsoft Harri Online (Natural) - Finnish (Finland) (fi-FI)', value: 'Microsoft Harri Online (Natural) - Finnish (Finland)'}, 
{text: 'Microsoft Noora Online (Natural) - Finnish (Finland) (fi-FI)', value: 'Microsoft Noora Online (Natural) - Finnish (Finland)'}, 
{text: 'Microsoft Charline Online (Natural) - French (Belgium) (fr-BE)', value: 'Microsoft Charline Online (Natural) - French (Belgium)'}, 
{text: 'Microsoft Gerard Online (Natural) - French (Belgium) (fr-BE)', value: 'Microsoft Gerard Online (Natural) - French (Belgium)'}, 
{text: 'Microsoft Thierry Online (Natural) - French (Canada) (fr-CA)', value: 'Microsoft Thierry Online (Natural) - French (Canada)'}, 
{text: 'Microsoft Antoine Online (Natural) - French (Canada) (fr-CA)', value: 'Microsoft Antoine Online (Natural) - French (Canada)'}, 
{text: 'Microsoft Jean Online (Natural) - French (Canada) (fr-CA)', value: 'Microsoft Jean Online (Natural) - French (Canada)'}, 
{text: 'Microsoft Sylvie Online (Natural) - French (Canada) (fr-CA)', value: 'Microsoft Sylvie Online (Natural) - French (Canada)'}, 
{text: 'Microsoft VivienneMultilingual Online (Natural) - French (France) (fr-FR)', value: 'Microsoft VivienneMultilingual Online (Natural) - French (France)'}, 
{text: 'Microsoft RemyMultilingual Online (Natural) - French (France) (fr-FR)', value: 'Microsoft RemyMultilingual Online (Natural) - French (France)'}, 
{text: 'Microsoft Denise Online (Natural) - French (France) (fr-FR)', value: 'Microsoft Denise Online (Natural) - French (France)'}, 
{text: 'Microsoft Eloise Online (Natural) - French (France) (fr-FR)', value: 'Microsoft Eloise Online (Natural) - French (France)'}, 
{text: 'Microsoft Henri Online (Natural) - French (France) (fr-FR)', value: 'Microsoft Henri Online (Natural) - French (France)'}, 
{text: 'Microsoft Ariane Online (Natural) - French (Switzerland) (fr-CH)', value: 'Microsoft Ariane Online (Natural) - French (Switzerland)'}, 
{text: 'Microsoft Fabrice Online (Natural) - French (Switzerland) (fr-CH)', value: 'Microsoft Fabrice Online (Natural) - French (Switzerland)'}, 
{text: 'Microsoft Roi Online (Natural) - Galician (gl-ES)', value: 'Microsoft Roi Online (Natural) - Galician'}, 
{text: 'Microsoft Sabela Online (Natural) - Galician (gl-ES)', value: 'Microsoft Sabela Online (Natural) - Galician'}, 
{text: 'Microsoft Eka Online (Natural) - Georgian (Georgia) (ka-GE)', value: 'Microsoft Eka Online (Natural) - Georgian (Georgia)'}, 
{text: 'Microsoft Giorgi Online (Natural) - Georgian (Georgia) (ka-GE)', value: 'Microsoft Giorgi Online (Natural) - Georgian (Georgia)'}, 
{text: 'Microsoft Ingrid Online (Natural) - German (Austria) (de-AT)', value: 'Microsoft Ingrid Online (Natural) - German (Austria)'}, 
{text: 'Microsoft Jonas Online (Natural) - German (Austria) (de-AT)', value: 'Microsoft Jonas Online (Natural) - German (Austria)'}, 
{text: 'Microsoft SeraphinaMultilingual Online (Natural) - German (Germany) (de-DE)', value: 'Microsoft SeraphinaMultilingual Online (Natural) - German (Germany)'}, 
{text: 'Microsoft FlorianMultilingual Online (Natural) - German (Germany) (de-DE)', value: 'Microsoft FlorianMultilingual Online (Natural) - German (Germany)'}, 
{text: 'Microsoft Amala Online (Natural) - German (Germany) (de-DE)', value: 'Microsoft Amala Online (Natural) - German (Germany)'}, 
{text: 'Microsoft Conrad Online (Natural) - German (Germany) (de-DE)', value: 'Microsoft Conrad Online (Natural) - German (Germany)'}, 
{text: 'Microsoft Katja Online (Natural) - German (Germany) (de-DE)', value: 'Microsoft Katja Online (Natural) - German (Germany)'}, 
{text: 'Microsoft Killian Online (Natural) - German (Germany) (de-DE)', value: 'Microsoft Killian Online (Natural) - German (Germany)'}, 
{text: 'Microsoft Jan Online (Natural) - German (Switzerland) (de-CH)', value: 'Microsoft Jan Online (Natural) - German (Switzerland)'}, 
{text: 'Microsoft Leni Online (Natural) - German (Switzerland) (de-CH)', value: 'Microsoft Leni Online (Natural) - German (Switzerland)'}, 
{text: 'Microsoft Athina Online (Natural) - Greek (Greece) (el-GR)', value: 'Microsoft Athina Online (Natural) - Greek (Greece)'}, 
{text: 'Microsoft Nestoras Online (Natural) - Greek (Greece) (el-GR)', value: 'Microsoft Nestoras Online (Natural) - Greek (Greece)'}, 
{text: 'Microsoft Dhwani Online (Natural) - Gujarati (India) (gu-IN)', value: 'Microsoft Dhwani Online (Natural) - Gujarati (India)'}, 
{text: 'Microsoft Niranjan Online (Natural) - Gujarati (India) (gu-IN)', value: 'Microsoft Niranjan Online (Natural) - Gujarati (India)'}, 
{text: 'Microsoft Avri Online (Natural) - Hebrew (Israel) (he-IL)', value: 'Microsoft Avri Online (Natural) - Hebrew (Israel)'}, 
{text: 'Microsoft Hila Online (Natural) - Hebrew (Israel) (he-IL)', value: 'Microsoft Hila Online (Natural) - Hebrew (Israel)'}, 
{text: 'Microsoft Madhur Online (Natural) - Hindi (India) (hi-IN)', value: 'Microsoft Madhur Online (Natural) - Hindi (India)'}, 
{text: 'Microsoft Swara Online (Natural) - Hindi (India) (hi-IN)', value: 'Microsoft Swara Online (Natural) - Hindi (India)'}, 
{text: 'Microsoft Noemi Online (Natural) - Hungarian (Hungary) (hu-HU)', value: 'Microsoft Noemi Online (Natural) - Hungarian (Hungary)'}, 
{text: 'Microsoft Tamas Online (Natural) - Hungarian (Hungary) (hu-HU)', value: 'Microsoft Tamas Online (Natural) - Hungarian (Hungary)'}, 
{text: 'Microsoft Gudrun Online (Natural) - Icelandic (Iceland) (is-IS)', value: 'Microsoft Gudrun Online (Natural) - Icelandic (Iceland)'}, 
{text: 'Microsoft Gunnar Online (Natural) - Icelandic (Iceland) (is-IS)', value: 'Microsoft Gunnar Online (Natural) - Icelandic (Iceland)'}, 
{text: 'Microsoft Ardi Online (Natural) - Indonesian (Indonesia) (id-ID)', value: 'Microsoft Ardi Online (Natural) - Indonesian (Indonesia)'}, 
{text: 'Microsoft Gadis Online (Natural) - Indonesian (Indonesia) (id-ID)', value: 'Microsoft Gadis Online (Natural) - Indonesian (Indonesia)'}, 
{text: 'Microsoft Siqiniq Online (Natural) - Inuktitut (Latin, Canada) (iu-Latn-CA)', value: 'Microsoft Siqiniq Online (Natural) - Inuktitut (Latin, Canada)'}, 
{text: 'Microsoft Taqqiq Online (Natural) - Inuktitut (Latin, Canada) (iu-Latn-CA)', value: 'Microsoft Taqqiq Online (Natural) - Inuktitut (Latin, Canada)'}, 
{text: 'Microsoft Siqiniq Online (Natural) - Inuktitut (Syllabics, Canada) (iu-Cans-CA)', value: 'Microsoft Siqiniq Online (Natural) - Inuktitut (Syllabics, Canada)'}, 
{text: 'Microsoft Taqqiq Online (Natural) - Inuktitut (Syllabics, Canada) (iu-Cans-CA)', value: 'Microsoft Taqqiq Online (Natural) - Inuktitut (Syllabics, Canada)'}, 
{text: 'Microsoft Colm Online (Natural) - Irish (Ireland) (ga-IE)', value: 'Microsoft Colm Online (Natural) - Irish (Ireland)'}, 
{text: 'Microsoft Orla Online (Natural) - Irish (Ireland) (ga-IE)', value: 'Microsoft Orla Online (Natural) - Irish (Ireland)'}, 
{text: 'Microsoft GiuseppeMultilingual Online (Natural) - Italian (Italy) (it-IT)', value: 'Microsoft GiuseppeMultilingual Online (Natural) - Italian (Italy)'}, 
{text: 'Microsoft Diego Online (Natural) - Italian (Italy) (it-IT)', value: 'Microsoft Diego Online (Natural) - Italian (Italy)'}, 
{text: 'Microsoft Elsa Online (Natural) - Italian (Italy) (it-IT)', value: 'Microsoft Elsa Online (Natural) - Italian (Italy)'}, 
{text: 'Microsoft Isabella Online (Natural) - Italian (Italy) (it-IT)', value: 'Microsoft Isabella Online (Natural) - Italian (Italy)'}, 
{text: 'Microsoft Keita Online (Natural) - Japanese (Japan) (ja-JP)', value: 'Microsoft Keita Online (Natural) - Japanese (Japan)'}, 
{text: 'Microsoft Nanami Online (Natural) - Japanese (Japan) (ja-JP)', value: 'Microsoft Nanami Online (Natural) - Japanese (Japan)'}, 
{text: 'Microsoft Dimas Online (Natural) - Javanese (Indonesia) (jv-ID)', value: 'Microsoft Dimas Online (Natural) - Javanese (Indonesia)'}, 
{text: 'Microsoft Siti Online (Natural) - Javanese (Indonesia) (jv-ID)', value: 'Microsoft Siti Online (Natural) - Javanese (Indonesia)'}, 
{text: 'Microsoft Gagan Online (Natural) - Kannada (India) (kn-IN)', value: 'Microsoft Gagan Online (Natural) - Kannada (India)'}, 
{text: 'Microsoft Sapna Online (Natural) - Kannada (India) (kn-IN)', value: 'Microsoft Sapna Online (Natural) - Kannada (India)'}, 
{text: 'Microsoft Aigul Online (Natural) - Kazakh (Kazakhstan) (kk-KZ)', value: 'Microsoft Aigul Online (Natural) - Kazakh (Kazakhstan)'}, 
{text: 'Microsoft Daulet Online (Natural) - Kazakh (Kazakhstan) (kk-KZ)', value: 'Microsoft Daulet Online (Natural) - Kazakh (Kazakhstan)'}, 
{text: 'Microsoft Piseth Online (Natural) - Khmer (Cambodia) (km-KH)', value: 'Microsoft Piseth Online (Natural) - Khmer (Cambodia)'}, 
{text: 'Microsoft Sreymom Online (Natural) - Khmer (Cambodia) (km-KH)', value: 'Microsoft Sreymom Online (Natural) - Khmer (Cambodia)'}, 
{text: 'Microsoft HyunsuMultilingual Online (Natural) - Korean (Korea) (ko-KR)', value: 'Microsoft HyunsuMultilingual Online (Natural) - Korean (Korea)'}, 
{text: 'Microsoft InJoon Online (Natural) - Korean (Korea) (ko-KR)', value: 'Microsoft InJoon Online (Natural) - Korean (Korea)'}, 
{text: 'Microsoft SunHi Online (Natural) - Korean (Korea) (ko-KR)', value: 'Microsoft SunHi Online (Natural) - Korean (Korea)'}, 
{text: 'Microsoft Chanthavong Online (Natural) - Lao (Laos) (lo-LA)', value: 'Microsoft Chanthavong Online (Natural) - Lao (Laos)'}, 
{text: 'Microsoft Keomany Online (Natural) - Lao (Laos) (lo-LA)', value: 'Microsoft Keomany Online (Natural) - Lao (Laos)'}, 
{text: 'Microsoft Everita Online (Natural) - Latvian (Latvia) (lv-LV)', value: 'Microsoft Everita Online (Natural) - Latvian (Latvia)'}, 
{text: 'Microsoft Nils Online (Natural) - Latvian (Latvia) (lv-LV)', value: 'Microsoft Nils Online (Natural) - Latvian (Latvia)'}, 
{text: 'Microsoft Leonas Online (Natural) - Lithuanian (Lithuania) (lt-LT)', value: 'Microsoft Leonas Online (Natural) - Lithuanian (Lithuania)'}, 
{text: 'Microsoft Ona Online (Natural) - Lithuanian (Lithuania) (lt-LT)', value: 'Microsoft Ona Online (Natural) - Lithuanian (Lithuania)'}, 
{text: 'Microsoft Aleksandar Online (Natural) - Macedonian (North Macedonia) (mk-MK)', value: 'Microsoft Aleksandar Online (Natural) - Macedonian (North Macedonia)'}, 
{text: 'Microsoft Marija Online (Natural) - Macedonian (North Macedonia) (mk-MK)', value: 'Microsoft Marija Online (Natural) - Macedonian (North Macedonia)'}, 
{text: 'Microsoft Osman Online (Natural) - Malay (Malaysia) (ms-MY)', value: 'Microsoft Osman Online (Natural) - Malay (Malaysia)'}, 
{text: 'Microsoft Yasmin Online (Natural) - Malay (Malaysia) (ms-MY)', value: 'Microsoft Yasmin Online (Natural) - Malay (Malaysia)'}, 
{text: 'Microsoft Midhun Online (Natural) - Malayalam (India) (ml-IN)', value: 'Microsoft Midhun Online (Natural) - Malayalam (India)'}, 
{text: 'Microsoft Sobhana Online (Natural) - Malayalam (India) (ml-IN)', value: 'Microsoft Sobhana Online (Natural) - Malayalam (India)'}, 
{text: 'Microsoft Grace Online (Natural) - Maltese (Malta) (mt-MT)', value: 'Microsoft Grace Online (Natural) - Maltese (Malta)'}, 
{text: 'Microsoft Joseph Online (Natural) - Maltese (Malta) (mt-MT)', value: 'Microsoft Joseph Online (Natural) - Maltese (Malta)'}, 
{text: 'Microsoft Aarohi Online (Natural) - Marathi (India) (mr-IN)', value: 'Microsoft Aarohi Online (Natural) - Marathi (India)'}, 
{text: 'Microsoft Manohar Online (Natural) - Marathi (India) (mr-IN)', value: 'Microsoft Manohar Online (Natural) - Marathi (India)'}, 
{text: 'Microsoft Bataa Online (Natural) - Mongolian (Mongolia) (mn-MN)', value: 'Microsoft Bataa Online (Natural) - Mongolian (Mongolia)'}, 
{text: 'Microsoft Yesui Online (Natural) - Mongolian (Mongolia) (mn-MN)', value: 'Microsoft Yesui Online (Natural) - Mongolian (Mongolia)'}, 
{text: 'Microsoft Hemkala Online (Natural) - Nepali (Nepal) (ne-NP)', value: 'Microsoft Hemkala Online (Natural) - Nepali (Nepal)'}, 
{text: 'Microsoft Sagar Online (Natural) - Nepali (Nepal) (ne-NP)', value: 'Microsoft Sagar Online (Natural) - Nepali (Nepal)'}, 
{text: 'Microsoft Finn Online (Natural) - Norwegian (Bokmål Norway) (nb-NO)', value: 'Microsoft Finn Online (Natural) - Norwegian (Bokmål Norway)'}, 
{text: 'Microsoft Pernille Online (Natural) - Norwegian (Bokmål, Norway) (nb-NO)', value: 'Microsoft Pernille Online (Natural) - Norwegian (Bokmål, Norway)'}, 
{text: 'Microsoft GulNawaz Online (Natural) - Pashto (Afghanistan) (ps-AF)', value: 'Microsoft GulNawaz Online (Natural) - Pashto (Afghanistan)'}, 
{text: 'Microsoft Latifa Online (Natural) - Pashto (Afghanistan) (ps-AF)', value: 'Microsoft Latifa Online (Natural) - Pashto (Afghanistan)'}, 
{text: 'Microsoft Dilara Online (Natural) - Persian (Iran) (fa-IR)', value: 'Microsoft Dilara Online (Natural) - Persian (Iran)'}, 
{text: 'Microsoft Farid Online (Natural) - Persian (Iran) (fa-IR)', value: 'Microsoft Farid Online (Natural) - Persian (Iran)'}, 
{text: 'Microsoft Marek Online (Natural) - Polish (Poland) (pl-PL)', value: 'Microsoft Marek Online (Natural) - Polish (Poland)'}, 
{text: 'Microsoft Zofia Online (Natural) - Polish (Poland) (pl-PL)', value: 'Microsoft Zofia Online (Natural) - Polish (Poland)'}, 
{text: 'Microsoft ThalitaMultilingual Online (Natural) - Portuguese (Brazil) (pt-BR)', value: 'Microsoft ThalitaMultilingual Online (Natural) - Portuguese (Brazil)'}, 
{text: 'Microsoft Antonio Online (Natural) - Portuguese (Brazil) (pt-BR)', value: 'Microsoft Antonio Online (Natural) - Portuguese (Brazil)'}, 
{text: 'Microsoft Francisca Online (Natural) - Portuguese (Brazil) (pt-BR)', value: 'Microsoft Francisca Online (Natural) - Portuguese (Brazil)'}, 
{text: 'Microsoft Duarte Online (Natural) - Portuguese (Portugal) (pt-PT)', value: 'Microsoft Duarte Online (Natural) - Portuguese (Portugal)'}, 
{text: 'Microsoft Raquel Online (Natural) - Portuguese (Portugal) (pt-PT)', value: 'Microsoft Raquel Online (Natural) - Portuguese (Portugal)'}, 
{text: 'Microsoft Alina Online (Natural) - Romanian (Romania) (ro-RO)', value: 'Microsoft Alina Online (Natural) - Romanian (Romania)'}, 
{text: 'Microsoft Emil Online (Natural) - Romanian (Romania) (ro-RO)', value: 'Microsoft Emil Online (Natural) - Romanian (Romania)'}, 
{text: 'Microsoft Dmitry Online (Natural) - Russian (Russia) (ru-RU)', value: 'Microsoft Dmitry Online (Natural) - Russian (Russia)'}, 
{text: 'Microsoft Svetlana Online (Natural) - Russian (Russia) (ru-RU)', value: 'Microsoft Svetlana Online (Natural) - Russian (Russia)'}, 
{text: 'Microsoft Nicholas Online (Natural) - Serbian (Serbia) (sr-RS)', value: 'Microsoft Nicholas Online (Natural) - Serbian (Serbia)'}, 
{text: 'Microsoft Sophie Online (Natural) - Serbian (Serbia) (sr-RS)', value: 'Microsoft Sophie Online (Natural) - Serbian (Serbia)'}, 
{text: 'Microsoft Sameera Online (Natural) - Sinhala (Sri Lanka) (si-LK)', value: 'Microsoft Sameera Online (Natural) - Sinhala (Sri Lanka)'}, 
{text: 'Microsoft Thilini Online (Natural) - Sinhala (Sri Lanka) (si-LK)', value: 'Microsoft Thilini Online (Natural) - Sinhala (Sri Lanka)'}, 
{text: 'Microsoft Lukas Online (Natural) - Slovak (Slovakia) (sk-SK)', value: 'Microsoft Lukas Online (Natural) - Slovak (Slovakia)'}, 
{text: 'Microsoft Viktoria Online (Natural) - Slovak (Slovakia) (sk-SK)', value: 'Microsoft Viktoria Online (Natural) - Slovak (Slovakia)'}, 
{text: 'Microsoft Petra Online (Natural) - Slovenian (Slovenia) (sl-SI)', value: 'Microsoft Petra Online (Natural) - Slovenian (Slovenia)'}, 
{text: 'Microsoft Rok Online (Natural) - Slovenian (Slovenia) (sl-SI)', value: 'Microsoft Rok Online (Natural) - Slovenian (Slovenia)'}, 
{text: 'Microsoft Muuse Online (Natural) - Somali (Somalia) (so-SO)', value: 'Microsoft Muuse Online (Natural) - Somali (Somalia)'}, 
{text: 'Microsoft Ubax Online (Natural) - Somali (Somalia) (so-SO)', value: 'Microsoft Ubax Online (Natural) - Somali (Somalia)'}, 
{text: 'Microsoft Elena Online (Natural) - Spanish (Argentina) (es-AR)', value: 'Microsoft Elena Online (Natural) - Spanish (Argentina)'}, 
{text: 'Microsoft Tomas Online (Natural) - Spanish (Argentina) (es-AR)', value: 'Microsoft Tomas Online (Natural) - Spanish (Argentina)'}, 
{text: 'Microsoft Marcelo Online (Natural) - Spanish (Bolivia) (es-BO)', value: 'Microsoft Marcelo Online (Natural) - Spanish (Bolivia)'}, 
{text: 'Microsoft Sofia Online (Natural) - Spanish (Bolivia) (es-BO)', value: 'Microsoft Sofia Online (Natural) - Spanish (Bolivia)'}, 
{text: 'Microsoft Catalina Online (Natural) - Spanish (Chile) (es-CL)', value: 'Microsoft Catalina Online (Natural) - Spanish (Chile)'}, 
{text: 'Microsoft Lorenzo Online (Natural) - Spanish (Chile) (es-CL)', value: 'Microsoft Lorenzo Online (Natural) - Spanish (Chile)'}, 
{text: 'Microsoft Gonzalo Online (Natural) - Spanish (Colombia) (es-CO)', value: 'Microsoft Gonzalo Online (Natural) - Spanish (Colombia)'}, 
{text: 'Microsoft Salome Online (Natural) - Spanish (Colombia) (es-CO)', value: 'Microsoft Salome Online (Natural) - Spanish (Colombia)'}, 
{text: 'Microsoft Ximena Online (Natural) - Spanish (Colombia) (es-ES)', value: 'Microsoft Ximena Online (Natural) - Spanish (Colombia)'}, 
{text: 'Microsoft Juan Online (Natural) - Spanish (Costa Rica) (es-CR)', value: 'Microsoft Juan Online (Natural) - Spanish (Costa Rica)'}, 
{text: 'Microsoft Maria Online (Natural) - Spanish (Costa Rica) (es-CR)', value: 'Microsoft Maria Online (Natural) - Spanish (Costa Rica)'}, 
{text: 'Microsoft Belkys Online (Natural) - Spanish (Cuba) (es-CU)', value: 'Microsoft Belkys Online (Natural) - Spanish (Cuba)'}, 
{text: 'Microsoft Manuel Online (Natural) - Spanish (Cuba) (es-CU)', value: 'Microsoft Manuel Online (Natural) - Spanish (Cuba)'}, 
{text: 'Microsoft Emilio Online (Natural) - Spanish (Dominican Republic) (es-DO)', value: 'Microsoft Emilio Online (Natural) - Spanish (Dominican Republic)'}, 
{text: 'Microsoft Ramona Online (Natural) - Spanish (Dominican Republic) (es-DO)', value: 'Microsoft Ramona Online (Natural) - Spanish (Dominican Republic)'}, 
{text: 'Microsoft Andrea Online (Natural) - Spanish (Ecuador) (es-EC)', value: 'Microsoft Andrea Online (Natural) - Spanish (Ecuador)'}, 
{text: 'Microsoft Luis Online (Natural) - Spanish (Ecuador) (es-EC)', value: 'Microsoft Luis Online (Natural) - Spanish (Ecuador)'}, 
{text: 'Microsoft Lorena Online (Natural) - Spanish (El Salvador) (es-SV)', value: 'Microsoft Lorena Online (Natural) - Spanish (El Salvador)'}, 
{text: 'Microsoft Rodrigo Online (Natural) - Spanish (El Salvador) (es-SV)', value: 'Microsoft Rodrigo Online (Natural) - Spanish (El Salvador)'}, 
{text: 'Microsoft Javier Online (Natural) - Spanish (Equatorial Guinea) (es-GQ)', value: 'Microsoft Javier Online (Natural) - Spanish (Equatorial Guinea)'}, 
{text: 'Microsoft Teresa Online (Natural) - Spanish (Equatorial Guinea) (es-GQ)', value: 'Microsoft Teresa Online (Natural) - Spanish (Equatorial Guinea)'}, 
{text: 'Microsoft Andres Online (Natural) - Spanish (Guatemala) (es-GT)', value: 'Microsoft Andres Online (Natural) - Spanish (Guatemala)'}, 
{text: 'Microsoft Marta Online (Natural) - Spanish (Guatemala) (es-GT)', value: 'Microsoft Marta Online (Natural) - Spanish (Guatemala)'}, 
{text: 'Microsoft Carlos Online (Natural) - Spanish (Honduras) (es-HN)', value: 'Microsoft Carlos Online (Natural) - Spanish (Honduras)'}, 
{text: 'Microsoft Karla Online (Natural) - Spanish (Honduras) (es-HN)', value: 'Microsoft Karla Online (Natural) - Spanish (Honduras)'}, 
{text: 'Microsoft Dalia Online (Natural) - Spanish (Mexico) (es-MX)', value: 'Microsoft Dalia Online (Natural) - Spanish (Mexico)'}, 
{text: 'Microsoft Jorge Online (Natural) - Spanish (Mexico) (es-MX)', value: 'Microsoft Jorge Online (Natural) - Spanish (Mexico)'}, 
{text: 'Microsoft Federico Online (Natural) - Spanish (Nicaragua) (es-NI)', value: 'Microsoft Federico Online (Natural) - Spanish (Nicaragua)'}, 
{text: 'Microsoft Yolanda Online (Natural) - Spanish (Nicaragua) (es-NI)', value: 'Microsoft Yolanda Online (Natural) - Spanish (Nicaragua)'}, 
{text: 'Microsoft Margarita Online (Natural) - Spanish (Panama) (es-PA)', value: 'Microsoft Margarita Online (Natural) - Spanish (Panama)'}, 
{text: 'Microsoft Roberto Online (Natural) - Spanish (Panama) (es-PA)', value: 'Microsoft Roberto Online (Natural) - Spanish (Panama)'}, 
{text: 'Microsoft Mario Online (Natural) - Spanish (Paraguay) (es-PY)', value: 'Microsoft Mario Online (Natural) - Spanish (Paraguay)'}, 
{text: 'Microsoft Tania Online (Natural) - Spanish (Paraguay) (es-PY)', value: 'Microsoft Tania Online (Natural) - Spanish (Paraguay)'}, 
{text: 'Microsoft Alex Online (Natural) - Spanish (Peru) (es-PE)', value: 'Microsoft Alex Online (Natural) - Spanish (Peru)'}, 
{text: 'Microsoft Camila Online (Natural) - Spanish (Peru) (es-PE)', value: 'Microsoft Camila Online (Natural) - Spanish (Peru)'}, 
{text: 'Microsoft Karina Online (Natural) - Spanish (Puerto Rico) (es-PR)', value: 'Microsoft Karina Online (Natural) - Spanish (Puerto Rico)'}, 
{text: 'Microsoft Victor Online (Natural) - Spanish (Puerto Rico) (es-PR)', value: 'Microsoft Victor Online (Natural) - Spanish (Puerto Rico)'}, 
{text: 'Microsoft Alvaro Online (Natural) - Spanish (Spain) (es-ES)', value: 'Microsoft Alvaro Online (Natural) - Spanish (Spain)'}, 
{text: 'Microsoft Elvira Online (Natural) - Spanish (Spain) (es-ES)', value: 'Microsoft Elvira Online (Natural) - Spanish (Spain)'}, 
{text: 'Microsoft Alonso Online (Natural) - Spanish (United States) (es-US)', value: 'Microsoft Alonso Online (Natural) - Spanish (United States)'}, 
{text: 'Microsoft Paloma Online (Natural) - Spanish (United States) (es-US)', value: 'Microsoft Paloma Online (Natural) - Spanish (United States)'}, 
{text: 'Microsoft Mateo Online (Natural) - Spanish (Uruguay) (es-UY)', value: 'Microsoft Mateo Online (Natural) - Spanish (Uruguay)'}, 
{text: 'Microsoft Valentina Online (Natural) - Spanish (Uruguay) (es-UY)', value: 'Microsoft Valentina Online (Natural) - Spanish (Uruguay)'}, 
{text: 'Microsoft Paola Online (Natural) - Spanish (Venezuela) (es-VE)', value: 'Microsoft Paola Online (Natural) - Spanish (Venezuela)'}, 
{text: 'Microsoft Sebastian Online (Natural) - Spanish (Venezuela) (es-VE)', value: 'Microsoft Sebastian Online (Natural) - Spanish (Venezuela)'}, 
{text: 'Microsoft Jajang Online (Natural) - Sundanese (Indonesia) (su-ID)', value: 'Microsoft Jajang Online (Natural) - Sundanese (Indonesia)'}, 
{text: 'Microsoft Tuti Online (Natural) - Sundanese (Indonesia) (su-ID)', value: 'Microsoft Tuti Online (Natural) - Sundanese (Indonesia)'}, 
{text: 'Microsoft Rafiki Online (Natural) - Swahili (Kenya) (sw-KE)', value: 'Microsoft Rafiki Online (Natural) - Swahili (Kenya)'}, 
{text: 'Microsoft Zuri Online (Natural) - Swahili (Kenya) (sw-KE)', value: 'Microsoft Zuri Online (Natural) - Swahili (Kenya)'}, 
{text: 'Microsoft Daudi Online (Natural) - Swahili (Tanzania) (sw-TZ)', value: 'Microsoft Daudi Online (Natural) - Swahili (Tanzania)'}, 
{text: 'Microsoft Rehema Online (Natural) - Swahili (Tanzania) (sw-TZ)', value: 'Microsoft Rehema Online (Natural) - Swahili (Tanzania)'}, 
{text: 'Microsoft Mattias Online (Natural) - Swedish (Sweden) (sv-SE)', value: 'Microsoft Mattias Online (Natural) - Swedish (Sweden)'}, 
{text: 'Microsoft Sofie Online (Natural) - Swedish (Sweden) (sv-SE)', value: 'Microsoft Sofie Online (Natural) - Swedish (Sweden)'}, 
{text: 'Microsoft Pallavi Online (Natural) - Tamil (India) (ta-IN)', value: 'Microsoft Pallavi Online (Natural) - Tamil (India)'}, 
{text: 'Microsoft Valluvar Online (Natural) - Tamil (India) (ta-IN)', value: 'Microsoft Valluvar Online (Natural) - Tamil (India)'}, 
{text: 'Microsoft Kani Online (Natural) - Tamil (Malaysia) (ta-MY)', value: 'Microsoft Kani Online (Natural) - Tamil (Malaysia)'}, 
{text: 'Microsoft Surya Online (Natural) - Tamil (Malaysia) (ta-MY)', value: 'Microsoft Surya Online (Natural) - Tamil (Malaysia)'}, 
{text: 'Microsoft Anbu Online (Natural) - Tamil (Singapore) (ta-SG)', value: 'Microsoft Anbu Online (Natural) - Tamil (Singapore)'}, 
{text: 'Microsoft Venba Online (Natural) - Tamil (Singapore) (ta-SG)', value: 'Microsoft Venba Online (Natural) - Tamil (Singapore)'}, 
{text: 'Microsoft Kumar Online (Natural) - Tamil (Sri Lanka) (ta-LK)', value: 'Microsoft Kumar Online (Natural) - Tamil (Sri Lanka)'}, 
{text: 'Microsoft Saranya Online (Natural) - Tamil (Sri Lanka) (ta-LK)', value: 'Microsoft Saranya Online (Natural) - Tamil (Sri Lanka)'}, 
{text: 'Microsoft Mohan Online (Natural) - Telugu (India) (te-IN)', value: 'Microsoft Mohan Online (Natural) - Telugu (India)'}, 
{text: 'Microsoft Shruti Online (Natural) - Telugu (India) (te-IN)', value: 'Microsoft Shruti Online (Natural) - Telugu (India)'}, 
{text: 'Microsoft Niwat Online (Natural) - Thai (Thailand) (th-TH)', value: 'Microsoft Niwat Online (Natural) - Thai (Thailand)'}, 
{text: 'Microsoft Premwadee Online (Natural) - Thai (Thailand) (th-TH)', value: 'Microsoft Premwadee Online (Natural) - Thai (Thailand)'}, 
{text: 'Microsoft Emel Online (Natural) - Turkish (Turkey) (tr-TR)', value: 'Microsoft Emel Online (Natural) - Turkish (Turkey)'}, 
{text: 'Microsoft Ahmet Online (Natural) - Turkish (Türkiye) (tr-TR)', value: 'Microsoft Ahmet Online (Natural) - Turkish (Türkiye)'}, 
{text: 'Microsoft Ostap Online (Natural) - Ukrainian (Ukraine) (uk-UA)', value: 'Microsoft Ostap Online (Natural) - Ukrainian (Ukraine)'}, 
{text: 'Microsoft Polina Online (Natural) - Ukrainian (Ukraine) (uk-UA)', value: 'Microsoft Polina Online (Natural) - Ukrainian (Ukraine)'}, 
{text: 'Microsoft Gul Online (Natural) - Urdu (India) (ur-IN)', value: 'Microsoft Gul Online (Natural) - Urdu (India)'}, 
{text: 'Microsoft Salman Online (Natural) - Urdu (India) (ur-IN)', value: 'Microsoft Salman Online (Natural) - Urdu (India)'}, 
{text: 'Microsoft Asad Online (Natural) - Urdu (Pakistan) (ur-PK)', value: 'Microsoft Asad Online (Natural) - Urdu (Pakistan)'}, 
{text: 'Microsoft Uzma Online (Natural) - Urdu (Pakistan) (ur-PK)', value: 'Microsoft Uzma Online (Natural) - Urdu (Pakistan)'}, 
{text: 'Microsoft Madina Online (Natural) - Uzbek (Uzbekistan) (uz-UZ)', value: 'Microsoft Madina Online (Natural) - Uzbek (Uzbekistan)'}, 
{text: 'Microsoft Sardor Online (Natural) - Uzbek (Uzbekistan) (uz-UZ)', value: 'Microsoft Sardor Online (Natural) - Uzbek (Uzbekistan)'}, 
{text: 'Microsoft HoaiMy Online (Natural) - Vietnamese (Vietnam) (vi-VN)', value: 'Microsoft HoaiMy Online (Natural) - Vietnamese (Vietnam)'}, 
{text: 'Microsoft NamMinh Online (Natural) - Vietnamese (Vietnam) (vi-VN)', value: 'Microsoft NamMinh Online (Natural) - Vietnamese (Vietnam)'}, 
{text: 'Microsoft Aled Online (Natural) - Welsh (United Kingdom) (cy-GB)', value: 'Microsoft Aled Online (Natural) - Welsh (United Kingdom)'}, 
{text: 'Microsoft Nia Online (Natural) - Welsh (United Kingdom) (cy-GB)', value: 'Microsoft Nia Online (Natural) - Welsh (United Kingdom)'}, 
{text: 'Microsoft Thando Online (Natural) - Zulu (South Africa) (zu-ZA)', value: 'Microsoft Thando Online (Natural) - Zulu (South Africa)'}, 
{text: 'Microsoft Themba Online (Natural) - Zulu (South Africa) (zu-ZA)', value: 'Microsoft Themba Online (Natural) - Zulu (South Africa)'}
            ];
            // 默认选择第一项
            this.selectedVoice = this.voiceArr[0].value;
			// 默认语速
            this.rate = 1.0;
        }

        getInfo() {
            const svgIcon = "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAyNC4wLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0i5Zu+5bGCXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4Ig0KCSB2aWV3Qm94PSIwIDAgNDAgNDAiIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgMCAwIDQwIDQwOyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+DQo8c3R5bGUgdHlwZT0idGV4dC9jc3MiPg0KCS5zdDB7ZmlsbC1ydWxlOmV2ZW5vZGQ7Y2xpcC1ydWxlOmV2ZW5vZGQ7ZmlsbDojRkZGRkZGO30NCgkuc3Qxe2ZpbGw6Izc0MzlFQTt9DQoJLnN0MntlbmFibGUtYmFja2dyb3VuZDpuZXcgICAgO30NCgkuc3Qze2ZpbGw6IzFGOTFFMTt9DQoJLnN0NHtmaWxsOm5vbmU7c3Ryb2tlOiM0RDQzRkY7c3Ryb2tlLXdpZHRoOjAuNTt9DQoJLnN0NXtmaWxsOiM0RDQzRkY7fQ0KCS5zdDZ7ZmlsbDojRkZGRkZGO30NCjwvc3R5bGU+DQo8dGl0bGU+57yW57uEIDI0PC90aXRsZT4NCjxkZXNjPkNyZWF0ZWQgd2l0aCBTa2V0Y2guPC9kZXNjPg0KPC9zdmc+DQo=";

            return {
                id: 'WebTTS',
                name: '语音合成',
                iconURL: svgIcon,
                blocks: [
                    {
                        opcode: 'say',
                        blockType: Scratch.BlockType.COMMAND,
                        text: '用 [VOICE] 说： [STRING]',
                        arguments: {
                            VOICE: {
                                type: Scratch.ArgumentType.STRING,
                                menu: 'voices',
                                defaultValue: this.selectedVoice
                            },
                            STRING: {
                                type: Scratch.ArgumentType.STRING,
                                defaultValue: '你好'
                            }
                        },
                        iconURI: svgIcon
                    },
					{
                        opcode: 'setSpeed',
                        blockType: Scratch.BlockType.COMMAND,
                        text: '设置语速为 [RATE]',
                        arguments: {
                            RATE: {
                                type: Scratch.ArgumentType.NUMBER,
                                defaultValue: this.rate
                            }
                        }
                    }
                ],
                menus: {
                    voices: {
                        items: this.voiceArr,
                        acceptReporters: true
                    }
                }
            };
        }

        say({ VOICE, STRING }) {
            return new Promise(resolve => {
                const utter = new SpeechSynthesisUtterance(STRING);
				utter.rate = this.rate;
                const voice = window.speechSynthesis
                    .getVoices()
                    .find(v => v.name === VOICE);
                if (voice) utter.voice = voice;
                utter.onend = resolve;
                utter.onerror = resolve;
                window.speechSynthesis.speak(utter);
            });
        }

		setSpeed({ RATE }) {
            this.rate = RATE;
        }
		
    }

    Scratch.extensions.register(new WebTTS());
})(Scratch);
